// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT65unt6zcXHJ5zvDcI05tXwIOGVeULw0',
    appId: '1:484555162611:web:a83e07a8b6ad4f0bfa4886',
    messagingSenderId: '484555162611',
    projectId: 'our-love-diary-app',
    authDomain: 'our-love-diary-app.firebaseapp.com',
    databaseURL: 'https://our-love-diary-app-default-rtdb.firebaseio.com',
    storageBucket: 'our-love-diary-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmzR6UYsYo661ltGLQTrAxwTzgGwPjwuY',
    appId: '1:484555162611:android:9f7e1cb3939438c3fa4886',
    messagingSenderId: '484555162611',
    projectId: 'our-love-diary-app',
    databaseURL: 'https://our-love-diary-app-default-rtdb.firebaseio.com',
    storageBucket: 'our-love-diary-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuC-mj5WSfdsl4QSi5ayIOjE9HtI4rZoM',
    appId: '1:484555162611:ios:8f4ab4a0fca223cbfa4886',
    messagingSenderId: '484555162611',
    projectId: 'our-love-diary-app',
    databaseURL: 'https://our-love-diary-app-default-rtdb.firebaseio.com',
    storageBucket: 'our-love-diary-app.appspot.com',
    iosBundleId: 'com.example.minimalSocialMediaApp',
  );
}
